// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:472523481959:web:583db5e13adf955a4b45c2',
    messagingSenderId: '472523481959',
    projectId: 'llmtest-ec773',
    authDomain: 'llmtest-ec773.firebaseapp.com',
    storageBucket: 'llmtest-ec773.firebasestorage.app',
    measurementId: 'G-MTMJ7XW5FC',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:472523481959:android:c6581e1a9064d8a54b45c2',
    messagingSenderId: '472523481959',
    projectId: 'llmtest-ec773',
    storageBucket: 'llmtest-ec773.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:472523481959:ios:77d82ed93bff94b74b45c2',
    messagingSenderId: '472523481959',
    projectId: 'llmtest-ec773',
    storageBucket: 'llmtest-ec773.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:472523481959:ios:77d82ed93bff94b74b45c2',
    messagingSenderId: '472523481959',
    projectId: 'llmtest-ec773',
    storageBucket: 'llmtest-ec773.firebasestorage.app',
    iosBundleId: 'com.example.midtermProject',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY'),
    appId: '1:472523481959:web:7b975b6af594346c4b45c2',
    messagingSenderId: '472523481959',
    projectId: 'llmtest-ec773',
    authDomain: 'llmtest-ec773.firebaseapp.com',
    storageBucket: 'llmtest-ec773.firebasestorage.app',
    measurementId: 'G-3Q65Q7SHZM',
  );
}
